name: "News Print"
description: "Send RSS News feeds to a physical printer"
version: "1.0.0"
slug: "newsprint"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  printer: null
  rss: []
schema:
  printer: match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)
  rss:
    - serial_number: str
      url: str

